### ISSUE TITLE
Are they on to us? // 403 errors when downloading the "latest.zip"

### ISSUE THREAD

**Issue by DDzwiedziu** [Vazkii/CMPDL#5]
Java: 1.8.0_101-b13

Proton - http://pastebin.com/UziYtBkt

ME: Natural Energy - http://pastebin.com/HMFwdLXn

**Comment by DDzwiedziu** [comment]
Update: perhaps this was some temporary glitch. Today this problem is not happening.

**Comment by taleteller** [comment]
I cant get anything downloaded as well, seems broken with Error 403. Why cant we just pass a Curse ZIP file for input? That way it would be possible to select the version as well.

**Comment by lolorz13** [comment]
response code 403 means that access is forbidden, this could be due to a number of reason depending on the api implementation (some api's return error 403 on incorrect queries) however there did not seem to be any changes published on their now deprecated github repository that would have coincided with your issues afaik. does the problem persist on the latest release for you?

**Comment by AndyProk** [comment]
I'm getting the same issue again. I really wish there were a way to feed this the zip file the browser gives you when following the /files/latest link :-/

**Comment by 4legsam** [comment]
I got it to work by making your not on the curse.com page but on the curseforge.com page.

**Comment by Gambleon** [comment]
@4legsam solution worked, I was on the curse.com site. Thanks for the tip!

**Comment by DDzwiedziu** [comment]
Ok, let's not beat the dead horse.
